# Corne keyboard config

# OLED display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# ZMK Studio (enables /dev/ttyACM)
CONFIG_ZMK_STUDIO=y

# Uncomment to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Mouse / pointing emulation
CONFIG_ZMK_POINTING=y

# Bluetooth settings
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
